[package]
name = "hello-wgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.23", features = [ "derive" ] }
env_logger = "0.11"
log = "0.4"
pollster = "0.4"
sdl3 = { version = "0.14", features = [ "raw-window-handle" ] }
wgpu = "25.0"



